server.port=8091
spring.application.name=loans-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health

management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
info.app.name=loans-service
info.app.description=Loans microservice registered with Eureka
info.app.version=1.0.0

logging.level.org.springframework=info
logging.level.com.cognizant=debug
logging.level.com.netflix.discovery=info
